### ISSUE TITLE
Use tmpfs for log directories to reduce storage media wear

### ISSUE THREAD

**Issue by klutchell** [klutchell/balena-pihole#131]
- `/var/log/pihole.log`
- `/var/log/pihole-FTL.log`

Something like this in the compose file might help, or it might break something that expects directories to exist there.

```yml
services:
  pihole:
    tmpfs:
      - /var/log/
```
